development:
  adapter: postgresql
  encoding: unicode
  database: t_development
  pool: 5
  timeout: 5000
  username: admin
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: t_test
  pool: 5
  timeout: 5000
  username: admin
  password: admin
  
production:

